import type { MarkingColor } from "../lib/markings";

/** Deployment defaults. Existing users keep their locally customized list. */
const DEFAULT_MARKING_GROUPS: Array<[name: string, color: string]> = [
  ["Adultery", "#f9a8b8"],
  ["Authority of the Bible", "#93c5fd"],
  ["Baptism", "#7dd3fc"],
  ["Biblical Love", "#f9a8d4"],
  ["Blessings and Curses", "#fde68a"],
  ["Christian Clothing", "#d8b4fe"],
  ["Christian Offices", "#a5b4fc"],
  ["Communion", "#fca5a5"],
  ["Conditional Security", "#fdba74"],
  ["Dating", "#f0abfc"],
  ["Dietary Guidance", "#bef264"],
  ["Discipline", "#fcd34d"],
  ["Education", "#67e8f9"],
  ["Effective Prayer", "#c4b5fd"],
  ["Family Planning", "#fda4af"],
  ["First Day", "#fed7aa"],
  ["Flattery", "#fecdd3"],
  ["Free Will", "#99f6e4"],
  ["God's Judgment", "#fb7185"],
  ["Grace", "#bbf7d0"],
  ["Home Church", "#86efac"],
  ["Immutability", "#bfdbfe"],
  ["Jesus Christ's Deity", "#c7d2fe"],
  ["Jesus Christ's Humanity", "#fecaca"],
  ["Leadership", "#a7f3d0"],
  ["Longevity", "#d9f99d"],
  ["Man's Role", "#bae6fd"],
  ["Marriage", "#f5b7d2"],
  ["Music's Influence", "#e9d5ff"],
  ["No Fellowship", "#fdc4a8"],
  ["No One is Good", "#fda4a4"],
  ["Non-Resistance", "#a7f3e8"],
  ["Not Under the Law", "#ddd6fe"],
  ["Obey God's Commandments", "#fde047"],
  ["Obey Government Laws", "#cbd5e1"],
  ["Omnipotent", "#818cf8"],
  ["Omnipresent", "#60a5fa"],
  ["Omniscient", "#a78bfa"],
  ["Orderly Home", "#b7e4c7"],
  ["Ordinances", "#67d6e8"],
  ["Prince of this World", "#c4a7a7"],
  ["Providence", "#8dd3c7"],
  ["Renewing of the Mind", "#a5f3fc"],
  ["Repentance", "#fbbf8a"],
  ["Saved by Faith", "#86efac"],
  ["Sodomy", "#f59e9e"],
  ["Spirit of Prophecy", "#d8b4fe"],
  ["Spiritual Gifts", "#c084fc"],
  ["Spiritual Judgment", "#f0c36e"],
  ["Spiritual Rebirth", "#6ee7b7"],
  ["Temptation", "#fca5a5"],
  ["What is Life", "#5eead4"],
  ["Wine", "#e8a0bf"],
  ["Wisdom Cause", "#fef08a"],
  ["Wisdom Fruit", "#bef264"],
  ["Wisdom Origin", "#fcd34d"],
  ["Wisdom Value", "#fbbf24"],
  ["Woman's Role", "#fbcfe8"],
  ["Word of God", "#7dd3fc"],
  ["Worldly Wisdom", "#d6d3d1"],
];

function markingId(name: string): string {
  return name.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export const DEPLOYMENT_MARKING_COLORS: MarkingColor[] = DEFAULT_MARKING_GROUPS.map(([name, value]) => ({
  id: markingId(name),
  name,
  value,
}));
